on: push
permissions:
  id-token: write
  pages: write
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: check_out_code
        uses: actions/checkout@v4

      - name: install_pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: install_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: install_deps
        run: pnpm install

      - name: build_code
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
        run: pnpm run build

      - name: upload_files
        id: uploading
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.uploading.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-gh-pages
    steps:
      - name: deploy_files
        id: deployment
        uses: actions/deploy-pages@v4
